config/routes.rb
Rails.application.routes.draw do


  resources :appointments
  # resources :patients
  # resources :doctors
  namespace :doctors do
  	devise_for :users
  end
  namespace :patients do
  	devise_for :users
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/views/shared/_error.html.erb
<% if notice %>
	<!-- <div class="alert alert-success alert-dismissible alert_notice" role="alert">
	  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
	  <span aria-hidden="true">&times;</span>
	  </button> -->
	  <strong><%= notice %></strong>
	<!-- </div> -->
<% end %>

<% if alert %>
    <!-- <div class="alert alert-danger alert-dismissible alert_notice" role="alert">
		  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
		  <span aria-hidden="true">&times;</span>
		  </button> -->
		  <strong><%= alert %></strong>
		<!-- </div> -->
<% end %>

app/views/shared/_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
  </div>
</footer>

app/views/shared/_topbar.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Hospital Management</h3>
    <nav class="nav nav-masthead justify-content-center">

<!--
      <a class="nav-link active" href="#">Home</a>
      <a class="nav-link" href="#">Features</a>
      <a class="nav-link" href="#">Contact</a>

 -->
      <% if doctors_user_signed_in? %>
		    <a href="<%= destroy_doctors_user_session_url %>" data-method="delete" class="nav-link float-right">Logout</a>
			<% elsif patients_user_signed_in?%>
					<a href="<%= appointments_url %>" class="nav-link float-right">Appointment</a>
			    <a href="<%= destroy_doctors_user_session_url %>" data-method="delete" class="nav-link float-right">Logout</a>
			<% else %>
				<a href="<%= new_doctors_user_session_url %>" class="nav-link float-right" >Doctor Sign In</a>
				<a href="<%= new_patients_user_session_url %>" class="nav-link float-right" >Patient Sign In</a>
			<% end %>


    </nav>
  </div>
</header>